# CLUES HTCONDOR configuration
- name: "Edit /etc/hosts file"
  shell: |
    for i in `seq 1 {{NNODES}}`; do
      item="{{ vnode_prefix }}${i}";
      grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item} ${item}.localdomain" >> /etc/hosts;
    done
    
- copy:
    content: |
        {% for number in range(1, NNODES|int + 1) %}
        {{vnode_prefix}}{{number}}.localdomain
        {% endfor %}
    dest: "/etc/clues2/condor_vnodes.info"

- ini_file: dest=/etc/clues2/clues2.cfg section=general option=LRMS_CLASS value=cluesplugins.condor
  notify: restart cluesd
