- name: Generate vnodes files
  template: src=vnodes.j2 dest="/etc/clues2/kubernetes_vnodes.info"
  vars:
    vnode_suffix: ".localdomain"

- name: Set Kubernetes as CLUES2 LRMS
  ini_file: dest=/etc/clues2/clues2.cfg section=general option=LRMS_CLASS value=cluesplugins.kubernetes
  notify: restart cluesd

- name: Create Kubernetes plugin configuration file for CLUES2
  copy: src=/etc/clues2/conf.d/plugin-kubernetes.cfg-example dest=/etc/clues2/conf.d/plugin-kubernetes.cfg force=no remote_src=yes
  notify: restart cluesd

- name: Set Insecure KUBERNETES_SERVER value
  ini_file: dest=/etc/clues2/conf.d/plugin-kubernetes.cfg section=KUBERNETES option=KUBERNETES_SERVER value="http://localhost:8080"
  notify: restart cluesd
  when: KUBERNETES_TOKEN is not defined

- name: Set Secure KUBERNETES_SERVER value
  ini_file: dest=/etc/clues2/conf.d/plugin-kubernetes.cfg section=KUBERNETES option=KUBERNETES_SERVER value="https://localhost:6443"
  notify: restart cluesd
  when: KUBERNETES_TOKEN is defined

- name: Set KUBERNETES_TOKEN value
  ini_file: dest=/etc/clues2/conf.d/plugin-kubernetes.cfg section=KUBERNETES option=KUBERNETES_TOKEN value={{KUBERNETES_TOKEN}}
  notify: restart cluesd
  when: KUBERNETES_TOKEN is defined

- name: Set KUBERNETES_PODS_API_URL_PATH value 
  ini_file: dest=/etc/clues2/conf.d/plugin-kubernetes.cfg section=KUBERNETES option=KUBERNETES_PODS_API_URL_PATH value={{KUBERNETES_PODS_API_URL_PATH}}
  notify: restart cluesd
  when: KUBERNETES_PODS_API_URL_PATH is defined

- name: Set KUBERNETES_NODES_API_URL_PATH value 
  ini_file: dest=/etc/clues2/conf.d/plugin-kubernetes.cfg section=KUBERNETES option=KUBERNETES_NODES_API_URL_PATH value={{KUBERNETES_NODES_API_URL_PATH}}
  notify: restart cluesd
  when: KUBERNETES_NODES_API_URL_PATH is defined  

- name: Set KUBERNETES_NODE_MEMORY value 
  ini_file: dest=/etc/clues2/conf.d/plugin-kubernetes.cfg section=KUBERNETES option=KUBERNETES_NODE_MEMORY value={{KUBERNETES_NODE_MEMORY}}
  notify: restart cluesd
  when: KUBERNETES_NODE_MEMORY is defined  

- name: Set KUBERNETES_NODE_SLOTS value 
  ini_file: dest=/etc/clues2/conf.d/plugin-kubernetes.cfg section=KUBERNETES option=KUBERNETES_NODE_SLOTS value={{KUBERNETES_NODE_SLOTS}}
  notify: restart cluesd
  when: KUBERNETES_NODE_SLOTS is defined  

- name: Set KUBERNETES_NODE_PODS value 
  ini_file: dest=/etc/clues2/conf.d/plugin-kubernetes.cfg section=KUBERNETES option=KUBERNETES_NODE_PODS value={{KUBERNETES_NODE_PODS}}
  notify: restart cluesd
  when: KUBERNETES_NODE_PODS is defined  

# Add hooks to drain first and delete after the kube nodes
- name: Create Hooks configuration file for CLUES2
  copy: src=/etc/clues2/conf.d/hooks.cfg-example dest=/etc/clues2/conf.d/hooks.cfg force=no remote_src=yes
  notify: restart cluesd

- name: Create kube_drain.sh hook file for CLUES2
  copy: src=kube_drain.sh dest=/etc/clues2/scripts force=no mode='755'

- name: Create kube_delete.sh hook file for CLUES2
  copy: src=kube_delete.sh dest=/etc/clues2/scripts force=no mode='755'

- name: Set PRE_POWEROFF hook value
  ini_file: dest=/etc/clues2/conf.d/hooks.cfg section=hooks option=PRE_POWEROFF value="./kube_drain.sh"
  notify: restart cluesd

- name: Set POST_POWEROFF hook value
  ini_file: dest=/etc/clues2/conf.d/hooks.cfg section=hooks option=POST_POWEROFF value="./kube_delete.sh"
  notify: restart cluesd
